export enum Pages {
  Overview = "/",
  Accounts = "/accounts",
  RSU = "/rsu",
  TableView = "/table-view",
  BarChart = "/bar-chart",
  StackedBarChart = "/stacked-bar-chart",
  RangeIncomeExpense = "/range-income-expense",
  YTDChart = "/year-to-date-chart",
  AverageSpending = "/average-spending",
  Sankey = "/Sankey",
  Forecast = "/forecast",
  CSVFormats = "/csv-formats",
  SSDI = "/ssdi",
}
